'use client';

import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

interface GoalPdfData {
  goal: string;
  value: string;
  behaviorType: 'increase' | 'decrease';
  behavior: string;
  baseline: number;
  target: number;
  measurementMethod: string;
  fluencyEnabled: boolean;
  fluencySeconds: number;
  generalization: string[];
  maintenanceWeeks: number;
  qualityLevel: number;
}

export async function generateGoalPdf(data: GoalPdfData): Promise<Blob> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]); // Letter size
  
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  
  const { width, height } = page.getSize();
  const margin = 50;
  let y = height - margin;
  
  // Header
  page.drawText('IEP Behavior Goal', {
    x: margin,
    y,
    size: 24,
    font: helveticaBold,
    color: rgb(0.01, 0.47, 0.34), // emerald-700
  });
  y -= 20;
  
  page.drawText('Generated by Behavior School - behaviorschool.com/iep-goals', {
    x: margin,
    y,
    size: 10,
    font: helvetica,
    color: rgb(0.4, 0.4, 0.4),
  });
  y -= 35;
  
  // Quality Level Badge
  const levelLabels = ['', 'Basic Goal', 'With Baseline', 'With Fluency', 'With Generalization', 'Complete SMART Goal'];
  page.drawText(`Goal Level: ${data.qualityLevel}/5 - ${levelLabels[data.qualityLevel]}`, {
    x: margin,
    y,
    size: 12,
    font: helveticaBold,
    color: data.qualityLevel >= 4 ? rgb(0.01, 0.47, 0.34) : rgb(0.6, 0.4, 0),
  });
  y -= 25;
  
  // Horizontal line
  page.drawLine({
    start: { x: margin, y },
    end: { x: width - margin, y },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85),
  });
  y -= 25;
  
  // Student Value Section
  page.drawText('Student Value:', {
    x: margin,
    y,
    size: 11,
    font: helveticaBold,
    color: rgb(0.2, 0.2, 0.2),
  });
  page.drawText(data.value, {
    x: margin + 90,
    y,
    size: 11,
    font: helvetica,
    color: rgb(0.3, 0.3, 0.3),
  });
  y -= 20;
  
  // Target Behavior Section
  page.drawText('Target Behavior:', {
    x: margin,
    y,
    size: 11,
    font: helveticaBold,
    color: rgb(0.2, 0.2, 0.2),
  });
  page.drawText(`${data.behaviorType === 'increase' ? 'Increase' : 'Decrease'} - ${data.behavior}`, {
    x: margin + 95,
    y,
    size: 11,
    font: helvetica,
    color: rgb(0.3, 0.3, 0.3),
  });
  y -= 30;
  
  // Full Goal Section
  page.drawText('COMPLETE GOAL:', {
    x: margin,
    y,
    size: 12,
    font: helveticaBold,
    color: rgb(0.01, 0.47, 0.34),
  });
  y -= 20;
  
  // Word wrap the goal text
  const goalLines = wrapText(data.goal, helvetica, 11, width - 2 * margin);
  for (const line of goalLines) {
    page.drawText(line, {
      x: margin,
      y,
      size: 11,
      font: helvetica,
      color: rgb(0.15, 0.15, 0.15),
    });
    y -= 16;
  }
  y -= 20;
  
  // Goal Components Section
  page.drawText('GOAL COMPONENTS:', {
    x: margin,
    y,
    size: 12,
    font: helveticaBold,
    color: rgb(0.01, 0.47, 0.34),
  });
  y -= 20;
  
  const components = [
    { label: 'Baseline', value: `${data.baseline}% of opportunities`, included: true },
    { label: 'Target', value: `${data.target}% of opportunities`, included: true },
    { label: 'Measurement', value: data.measurementMethod, included: true },
    { label: 'Fluency', value: data.fluencyEnabled ? `Within ${data.fluencySeconds} seconds` : 'Not included', included: data.fluencyEnabled },
    { label: 'Generalization', value: data.generalization.length > 0 ? `${data.generalization.length} settings` : 'Not included', included: data.generalization.length > 0 },
    { label: 'Maintenance', value: `${data.maintenanceWeeks} weeks`, included: true },
  ];
  
  for (const comp of components) {
    const checkmark = comp.included ? '✓' : '○';
    const color = comp.included ? rgb(0.01, 0.47, 0.34) : rgb(0.6, 0.6, 0.6);
    page.drawText(`${checkmark} ${comp.label}: ${comp.value}`, {
      x: margin,
      y,
      size: 10,
      font: helvetica,
      color,
    });
    y -= 15;
  }
  y -= 20;
  
  // Settings Section
  if (data.generalization.length > 0) {
    page.drawText('GENERALIZATION SETTINGS:', {
      x: margin,
      y,
      size: 11,
      font: helveticaBold,
      color: rgb(0.3, 0.3, 0.3),
    });
    y -= 18;
    
    for (const setting of data.generalization) {
      page.drawText(`• ${setting}`, {
        x: margin + 10,
        y,
        size: 10,
        font: helvetica,
        color: rgb(0.4, 0.4, 0.4),
      });
      y -= 14;
    }
    y -= 15;
  }
  
  // Footer
  const footerY = 50;
  page.drawLine({
    start: { x: margin, y: footerY + 15 },
    end: { x: width - margin, y: footerY + 15 },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85),
  });
  
  page.drawText(`Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, {
    x: margin,
    y: footerY,
    size: 9,
    font: helvetica,
    color: rgb(0.5, 0.5, 0.5),
  });
  
  page.drawText('Behavior School | behaviorschool.com', {
    x: width - margin - 150,
    y: footerY,
    size: 9,
    font: helvetica,
    color: rgb(0.5, 0.5, 0.5),
  });
  
  const pdfBytes = await pdfDoc.save();
  return new Blob([pdfBytes.buffer as ArrayBuffer], { type: 'application/pdf' });
}

function wrapText(text: string, _font: import('pdf-lib').PDFFont, _fontSize: number, maxWidth: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';
  
  // Approximate character width for Helvetica at 11pt
  const charWidth = 5.5;
  const maxChars = Math.floor(maxWidth / charWidth);
  
  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    if (testLine.length > maxChars && currentLine) {
      lines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  }
  if (currentLine) {
    lines.push(currentLine);
  }
  
  return lines;
}
