[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "9.12.3"
  ENABLE_EXPERIMENTAL_COREPACK = "1"
  NPM_FLAGS = "--prefer-offline --no-audit"
  PNPM_FLAGS = "--no-frozen-lockfile"
  SECRETS_SCAN_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Auto-submit sitemap to search engines after successful publish
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    sitemapUrl = "https://behaviorschool.com/sitemap.xml"
    providers = ["google", "bing"]

# Next.js handles routing, only redirect specific cases
[[redirects]]
  from = "/www/*"
  to = "/:splat"
  status = 301
  force = true

# Handle old URLs if any
[[redirects]]
  from = "/old-page"
  to = "/"
  status = 301

# Redirect supervision to supervisors
[[redirects]]
  from = "/supervision"
  to = "/supervisors"
  status = 301

# Redirect old school behavior support page to transformation program
[[redirects]]
  from = "/school-based-behavior-support"
  to = "/transformation-program"
  status = 301

[functions]
  node_bundler = "esbuild"
  external_node_modules = []
