[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "9.12.3"
  ENABLE_EXPERIMENTAL_COREPACK = "1"
  NPM_FLAGS = "--prefer-offline --no-audit"
  SECRETS_SCAN_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js handles routing, only redirect specific cases
[[redirects]]
  from = "/www/*"
  to = "/:splat"
  status = 301
  force = true

# Handle old URLs if any
[[redirects]]
  from = "/old-page"
  to = "/"
  status = 301

[functions]
  node_bundler = "esbuild"
  external_node_modules = []