[build]
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "20"
  ENABLE_EXPERIMENTAL_COREPACK = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[build.processing]
  skip_processing = true