export interface IEPGoal {
  id: number;
  category: string;
  subcategory: string;
  gradeLevel: string[];
  condition: string;
  behavior: string;
  criteria: string;
  goal: string;
}

export const categories = [
  "Behavior Reduction",
  "Social Skills",
  "Self-Regulation",
  "Communication",
  "Academic Engagement",
  "Daily Living / Independence",
] as const;

export const gradeLevels = ["PreK", "Elementary", "Middle", "High"] as const;

export const goals: IEPGoal[] = [
  // ========== BEHAVIOR REDUCTION ==========
  // Aggression
  { id: 1, category: "Behavior Reduction", subcategory: "Aggression", gradeLevel: ["PreK", "Elementary"], condition: "When frustrated or denied a preferred item/activity", behavior: "the student will use a replacement behavior (e.g., requesting a break, using words to express frustration) instead of engaging in physical aggression (hitting, kicking, biting)", criteria: "reducing aggressive incidents to no more than 1 per week across 4 consecutive weeks, as measured by staff incident reports." },
  { id: 2, category: "Behavior Reduction", subcategory: "Aggression", gradeLevel: ["Elementary", "Middle"], condition: "During unstructured activities (recess, lunch, transitions)", behavior: "the student will keep hands, feet, and objects to self", criteria: "with no more than 2 incidents of physical aggression per month for 3 consecutive months, as measured by behavior tracking data." },
  { id: 3, category: "Behavior Reduction", subcategory: "Aggression", gradeLevel: ["Middle", "High"], condition: "When experiencing a conflict with a peer", behavior: "the student will use a problem-solving strategy (walk away, talk it out, seek adult help) instead of verbal or physical aggression", criteria: "in 4 out of 5 conflict situations across 3 consecutive data collection periods, as measured by staff observation." },
  // Elopement
  { id: 4, category: "Behavior Reduction", subcategory: "Elopement", gradeLevel: ["PreK", "Elementary"], condition: "During classroom instruction and transitions", behavior: "the student will remain within the designated area without attempting to leave", criteria: "for 100% of the school day across 10 consecutive school days, as measured by staff monitoring logs." },
  { id: 5, category: "Behavior Reduction", subcategory: "Elopement", gradeLevel: ["Elementary", "Middle"], condition: "When feeling overwhelmed or wanting to avoid a non-preferred task", behavior: "the student will request a break or use a coping strategy instead of leaving the assigned area without permission", criteria: "reducing elopement to 0 incidents per week for 4 consecutive weeks, as measured by incident reports." },
  { id: 6, category: "Behavior Reduction", subcategory: "Elopement", gradeLevel: ["PreK"], condition: "During outdoor activities and transitions between settings", behavior: "the student will stay with the group and follow adult directions to stop", criteria: "responding to the adult's directive within 5 seconds in 4 out of 5 opportunities across 5 consecutive school days, as measured by teacher data." },
  // Self-Injury
  { id: 7, category: "Behavior Reduction", subcategory: "Self-Injury", gradeLevel: ["PreK", "Elementary"], condition: "When presented with a difficult task or during periods of high frustration", behavior: "the student will use a replacement behavior (squeeze ball, request help, take a break) instead of engaging in self-injurious behavior (head hitting, biting self, scratching self)", criteria: "reducing SIB to no more than 1 incident per day across 10 consecutive school days, as measured by ABC data collection." },
  { id: 8, category: "Behavior Reduction", subcategory: "Self-Injury", gradeLevel: ["Elementary", "Middle"], condition: "When experiencing sensory overload or emotional distress", behavior: "the student will independently access a sensory tool or calming strategy from their toolkit instead of engaging in self-harm", criteria: "in 80% of observed opportunities across 4 consecutive weeks, as measured by staff observation and behavior logs." },
  // Task Refusal
  { id: 9, category: "Behavior Reduction", subcategory: "Task Refusal", gradeLevel: ["Elementary", "Middle"], condition: "When presented with a non-preferred academic task", behavior: "the student will begin the task within 2 minutes of the directive, with or without adult support", criteria: "in 4 out of 5 opportunities per day across 10 consecutive school days, as measured by teacher data collection." },
  { id: 10, category: "Behavior Reduction", subcategory: "Task Refusal", gradeLevel: ["Middle", "High"], condition: "When given a classroom assignment or homework task", behavior: "the student will attempt the task (complete at least 50% of the work) before requesting modifications or assistance", criteria: "in 80% of task presentations across 3 consecutive weeks, as measured by work completion logs." },
  { id: 11, category: "Behavior Reduction", subcategory: "Task Refusal", gradeLevel: ["PreK", "Elementary"], condition: "During group instruction or individual work time", behavior: "the student will follow teacher directives to complete assigned activities", criteria: "complying with 4 out of 5 directives per session across 10 consecutive school days, as measured by teacher tally data." },
  // Disruption
  { id: 12, category: "Behavior Reduction", subcategory: "Disruption", gradeLevel: ["Elementary", "Middle"], condition: "During whole-group instruction", behavior: "the student will refrain from calling out, making noises, or leaving their seat without permission", criteria: "with no more than 2 disruptions per class period for 4 consecutive weeks, as measured by teacher frequency data." },
  { id: 13, category: "Behavior Reduction", subcategory: "Disruption", gradeLevel: ["Middle", "High"], condition: "During class discussions and lectures", behavior: "the student will raise their hand and wait to be called on before speaking", criteria: "in 80% of opportunities across 10 consecutive class sessions, as measured by teacher observation data." },
  { id: 14, category: "Behavior Reduction", subcategory: "Disruption", gradeLevel: ["PreK", "Elementary"], condition: "During circle time or story time", behavior: "the student will sit in their designated spot and keep their body calm", criteria: "for at least 10 minutes per session in 4 out of 5 sessions across 2 consecutive weeks, as measured by timer and teacher data." },
  // Property Destruction
  { id: 15, category: "Behavior Reduction", subcategory: "Property Destruction", gradeLevel: ["Elementary", "Middle"], condition: "When frustrated or angry", behavior: "the student will express their emotions verbally or through a coping strategy instead of throwing, breaking, or damaging materials", criteria: "reducing property destruction to 0 incidents per week for 4 consecutive weeks, as measured by incident reports." },
  { id: 16, category: "Behavior Reduction", subcategory: "Property Destruction", gradeLevel: ["PreK", "Elementary"], condition: "During transitions or when a preferred activity ends", behavior: "the student will handle classroom materials appropriately (put down gently, place in designated area)", criteria: "in 4 out of 5 transitions per day across 10 consecutive school days, as measured by teacher observation." },
  // Inappropriate Language
  { id: 17, category: "Behavior Reduction", subcategory: "Inappropriate Language", gradeLevel: ["Middle", "High"], condition: "During interactions with peers and adults", behavior: "the student will use school-appropriate language, refraining from profanity, name-calling, or verbal threats", criteria: "with no more than 1 incident per week across 4 consecutive weeks, as measured by staff documentation." },
  { id: 18, category: "Behavior Reduction", subcategory: "Inappropriate Language", gradeLevel: ["Elementary", "Middle"], condition: "When angry, frustrated, or in conflict with a peer", behavior: "the student will use appropriate replacement phrases (e.g., 'I'm frustrated,' 'I need space') instead of swearing or name-calling", criteria: "in 80% of observed situations across 4 consecutive weeks, as measured by behavior tracking data." },
  // Non-Compliance
  { id: 19, category: "Behavior Reduction", subcategory: "Non-Compliance", gradeLevel: ["Elementary", "Middle"], condition: "When given a directive by a staff member", behavior: "the student will comply with the adult direction within 1 minute, or appropriately request clarification or a modification", criteria: "in 80% of directives across 10 consecutive school days, as measured by compliance tracking data." },
  { id: 20, category: "Behavior Reduction", subcategory: "Non-Compliance", gradeLevel: ["PreK", "Elementary"], condition: "During daily routines (arrival, clean-up, transitions)", behavior: "the student will follow 2-step directions given by the teacher", criteria: "completing both steps within 2 minutes in 4 out of 5 opportunities per day across 2 consecutive weeks, as measured by teacher data." },

  // ========== SOCIAL SKILLS ==========
  // Peer Interaction
  { id: 21, category: "Social Skills", subcategory: "Peer Interaction", gradeLevel: ["PreK", "Elementary"], condition: "During free play or recess", behavior: "the student will initiate a social interaction with a peer (e.g., asking to play, offering a toy, making a comment about shared activity)", criteria: "at least 2 times per recess period across 10 consecutive school days, as measured by staff observation." },
  { id: 22, category: "Social Skills", subcategory: "Peer Interaction", gradeLevel: ["Elementary", "Middle"], condition: "During cooperative learning activities", behavior: "the student will participate appropriately with peers by taking turns, sharing materials, and contributing ideas", criteria: "in 4 out of 5 group activities per week across 4 consecutive weeks, as measured by teacher observation and rubric." },
  { id: 23, category: "Social Skills", subcategory: "Peer Interaction", gradeLevel: ["Middle", "High"], condition: "During unstructured social situations (lunch, passing periods, before/after school)", behavior: "the student will engage in a reciprocal conversation with a peer for at least 3 exchanges", criteria: "at least once per day across 10 consecutive school days, as measured by staff observation." },
  // Conversation Skills
  { id: 24, category: "Social Skills", subcategory: "Conversation Skills", gradeLevel: ["Elementary", "Middle"], condition: "During structured social skills lessons or naturalistic opportunities", behavior: "the student will maintain a conversation by asking a follow-up question or making a related comment", criteria: "for at least 4 conversational turns in 4 out of 5 opportunities across 3 consecutive weeks, as measured by staff data." },
  { id: 25, category: "Social Skills", subcategory: "Conversation Skills", gradeLevel: ["Middle", "High"], condition: "When engaging in conversation with peers or adults", behavior: "the student will demonstrate active listening skills (eye contact, nodding, not interrupting, responding to what was said)", criteria: "in 80% of observed conversations across 4 consecutive weeks, as measured by social skills rubric." },
  { id: 26, category: "Social Skills", subcategory: "Conversation Skills", gradeLevel: ["PreK", "Elementary"], condition: "During morning meeting or sharing time", behavior: "the student will listen to a peer's statement and respond with a relevant comment or question", criteria: "in 3 out of 5 opportunities per session across 2 consecutive weeks, as measured by teacher observation." },
  // Cooperation
  { id: 27, category: "Social Skills", subcategory: "Cooperation", gradeLevel: ["PreK", "Elementary"], condition: "During structured group activities", behavior: "the student will follow group rules and accept the ideas of others without arguing or withdrawing", criteria: "in 4 out of 5 group activities per week across 3 consecutive weeks, as measured by teacher observation." },
  { id: 28, category: "Social Skills", subcategory: "Cooperation", gradeLevel: ["Middle", "High"], condition: "When assigned a group project or collaborative task", behavior: "the student will contribute their fair share and compromise with peers when disagreements arise", criteria: "as rated 'satisfactory' or above by both teacher and peer feedback in 80% of group assignments across the grading period." },
  // Sharing
  { id: 29, category: "Social Skills", subcategory: "Sharing", gradeLevel: ["PreK", "Elementary"], condition: "When using shared classroom materials or during play", behavior: "the student will share materials with peers when asked, or offer to share without prompting", criteria: "in 4 out of 5 opportunities per day across 10 consecutive school days, as measured by teacher data." },
  // Personal Space
  { id: 30, category: "Social Skills", subcategory: "Personal Space", gradeLevel: ["PreK", "Elementary"], condition: "During all school settings (classroom, hallway, cafeteria)", behavior: "the student will maintain appropriate personal space (approximately arm's length) from peers and adults", criteria: "with no more than 2 verbal reminders per day across 10 consecutive school days, as measured by staff tally data." },
  { id: 31, category: "Social Skills", subcategory: "Personal Space", gradeLevel: ["Middle", "High"], condition: "During interactions with peers", behavior: "the student will recognize and respect others' personal boundaries, including physical space and personal belongings", criteria: "with 0 reported boundary violations per week for 4 consecutive weeks, as measured by staff and peer reports." },
  // Social Cues
  { id: 32, category: "Social Skills", subcategory: "Social Cues", gradeLevel: ["Elementary", "Middle"], condition: "During social interactions", behavior: "the student will identify and respond appropriately to nonverbal social cues (facial expressions, body language, tone of voice)", criteria: "correctly interpreting cues in 4 out of 5 presented scenarios across 3 consecutive weeks, as measured by social skills assessment." },
  { id: 33, category: "Social Skills", subcategory: "Social Cues", gradeLevel: ["Middle", "High"], condition: "When interacting with peers and adults", behavior: "the student will adjust their behavior based on social context (e.g., volume, topic, formality)", criteria: "demonstrating appropriate social awareness in 80% of observed interactions across 4 consecutive weeks, as measured by teacher and staff observation." },
  { id: 34, category: "Social Skills", subcategory: "Social Cues", gradeLevel: ["PreK", "Elementary"], condition: "During read-alouds or social stories", behavior: "the student will identify how a character is feeling based on facial expression and context", criteria: "correctly identifying emotions in 4 out of 5 opportunities across 5 consecutive sessions, as measured by teacher data." },

  // ========== SELF-REGULATION ==========
  // Emotional Regulation
  { id: 35, category: "Self-Regulation", subcategory: "Emotional Regulation", gradeLevel: ["PreK", "Elementary"], condition: "When experiencing strong emotions (anger, sadness, excitement)", behavior: "the student will identify their emotion using a visual support (feelings chart, zones of regulation) and select a calming strategy", criteria: "independently in 4 out of 5 opportunities across 10 consecutive school days, as measured by teacher observation." },
  { id: 36, category: "Self-Regulation", subcategory: "Emotional Regulation", gradeLevel: ["Elementary", "Middle"], condition: "When transitioning from a preferred to a non-preferred activity", behavior: "the student will manage their emotional response (no crying, yelling, or shutting down) and begin the new activity", criteria: "within 3 minutes in 80% of transitions across 4 consecutive weeks, as measured by teacher data." },
  { id: 37, category: "Self-Regulation", subcategory: "Emotional Regulation", gradeLevel: ["Middle", "High"], condition: "When receiving corrective feedback or a low grade", behavior: "the student will accept the feedback calmly (no arguing, eye-rolling, or shutting down) and ask a clarifying question or develop a plan for improvement", criteria: "in 4 out of 5 situations across 4 consecutive weeks, as measured by teacher observation." },
  // Coping Strategies
  { id: 38, category: "Self-Regulation", subcategory: "Coping Strategies", gradeLevel: ["PreK", "Elementary"], condition: "When feeling upset, anxious, or overwhelmed", behavior: "the student will independently select and use a coping strategy from their personal toolkit (deep breathing, counting, squeeze toy, quiet corner)", criteria: "in 4 out of 5 opportunities across 10 consecutive school days, as measured by teacher observation and self-monitoring checklist." },
  { id: 39, category: "Self-Regulation", subcategory: "Coping Strategies", gradeLevel: ["Elementary", "Middle"], condition: "When encountering a stressful academic or social situation", behavior: "the student will use at least one of three pre-taught coping strategies before the situation escalates", criteria: "in 80% of observed stressful situations across 4 consecutive weeks, as measured by behavior tracking data." },
  { id: 40, category: "Self-Regulation", subcategory: "Coping Strategies", gradeLevel: ["Middle", "High"], condition: "When feeling overwhelmed by workload or social pressure", behavior: "the student will independently implement a coping plan (break task into steps, use a planner, talk to a trusted adult, use breathing techniques)", criteria: "in 4 out of 5 opportunities across 3 consecutive weeks, as measured by self-report and teacher verification." },
  // Anger Management
  { id: 41, category: "Self-Regulation", subcategory: "Anger Management", gradeLevel: ["Elementary", "Middle"], condition: "When angered by a peer or situation", behavior: "the student will use a taught anger management strategy (walk away, count to 10, deep breaths, use an I-statement) instead of yelling, hitting, or throwing objects", criteria: "in 4 out of 5 anger-provoking situations across 4 consecutive weeks, as measured by staff observation and incident data." },
  { id: 42, category: "Self-Regulation", subcategory: "Anger Management", gradeLevel: ["Middle", "High"], condition: "When in a situation that triggers anger (perceived unfairness, conflict, being told no)", behavior: "the student will recognize their anger cues and remove themselves to a designated cool-down area before engaging in aggressive behavior", criteria: "in 80% of opportunities across 4 consecutive weeks, as measured by self-monitoring data and staff verification." },
  { id: 43, category: "Self-Regulation", subcategory: "Anger Management", gradeLevel: ["PreK", "Elementary"], condition: "When a peer takes a toy or doesn't share", behavior: "the student will use words (e.g., 'I don't like that,' 'Can I have a turn?') or seek adult help instead of hitting, grabbing, or screaming", criteria: "in 4 out of 5 opportunities across 10 consecutive school days, as measured by teacher data." },
  // Frustration Tolerance
  { id: 44, category: "Self-Regulation", subcategory: "Frustration Tolerance", gradeLevel: ["PreK", "Elementary"], condition: "When a task is difficult or the student makes an error", behavior: "the student will continue working on the task or ask for help instead of crying, throwing materials, or giving up", criteria: "in 4 out of 5 opportunities across 10 consecutive school days, as measured by teacher observation." },
  { id: 45, category: "Self-Regulation", subcategory: "Frustration Tolerance", gradeLevel: ["Elementary", "Middle"], condition: "When experiencing academic frustration (difficult problem, confusing directions)", behavior: "the student will try at least two strategies (re-read, ask a peer, raise hand for help) before disengaging from the task", criteria: "in 80% of frustrating academic situations across 3 consecutive weeks, as measured by teacher data." },
  { id: 46, category: "Self-Regulation", subcategory: "Frustration Tolerance", gradeLevel: ["Middle", "High"], condition: "When encountering setbacks in academic or extracurricular activities", behavior: "the student will demonstrate persistence by identifying what went wrong and creating a revised plan", criteria: "in 4 out of 5 setback situations across the grading period, as measured by teacher observation and student reflection logs." },
  // Self-Monitoring
  { id: 47, category: "Self-Regulation", subcategory: "Self-Monitoring", gradeLevel: ["Elementary", "Middle"], condition: "During independent work time", behavior: "the student will use a self-monitoring checklist to evaluate their on-task behavior at regular intervals (every 10 minutes)", criteria: "with 80% agreement between student self-rating and teacher rating across 10 consecutive school days." },
  { id: 48, category: "Self-Regulation", subcategory: "Self-Monitoring", gradeLevel: ["Middle", "High"], condition: "Throughout the school day", behavior: "the student will use a self-monitoring tool (point sheet, app, checklist) to track their behavior goals and reflect on their progress", criteria: "completing the self-monitoring tool with 90% accuracy for 4 consecutive weeks, as measured by teacher verification." },
  { id: 49, category: "Self-Regulation", subcategory: "Self-Monitoring", gradeLevel: ["PreK", "Elementary"], condition: "After completing an activity or during check-in times", behavior: "the student will use a visual scale (thumbs up/down, color chart) to rate how they are feeling and whether they followed expectations", criteria: "in 4 out of 5 check-in opportunities per day across 2 consecutive weeks, as measured by teacher data." },

  // ========== COMMUNICATION ==========
  // Requesting
  { id: 50, category: "Communication", subcategory: "Requesting", gradeLevel: ["PreK", "Elementary"], condition: "When wanting access to a preferred item, activity, or break", behavior: "the student will make an appropriate request using their communication system (verbal, PECS, AAC device, sign language)", criteria: "independently in 4 out of 5 opportunities across 10 consecutive school days, as measured by staff data collection." },
  { id: 51, category: "Communication", subcategory: "Requesting", gradeLevel: ["Elementary", "Middle"], condition: "During classroom activities", behavior: "the student will raise their hand or use an appropriate signal to request teacher attention, help, or materials", criteria: "in 80% of opportunities across 10 consecutive school days, as measured by teacher frequency data." },
  { id: 52, category: "Communication", subcategory: "Requesting", gradeLevel: ["PreK"], condition: "During snack time, play, or structured activities", behavior: "the student will use at least a one-word request or gesture to indicate wants and needs", criteria: "in 4 out of 5 opportunities per session across 10 consecutive school days, as measured by staff data." },
  // Protesting Appropriately
  { id: 53, category: "Communication", subcategory: "Protesting Appropriately", gradeLevel: ["PreK", "Elementary"], condition: "When presented with a non-preferred activity or when told 'no'", behavior: "the student will express their protest appropriately (saying 'no thank you,' 'I don't want to,' or using a break card) instead of crying, screaming, or dropping to the floor", criteria: "in 4 out of 5 opportunities across 10 consecutive school days, as measured by staff observation." },
  { id: 54, category: "Communication", subcategory: "Protesting Appropriately", gradeLevel: ["Elementary", "Middle"], condition: "When they disagree with a decision or rule", behavior: "the student will express their disagreement using respectful language and appropriate volume", criteria: "in 80% of situations across 4 consecutive weeks, as measured by teacher observation data." },
  { id: 55, category: "Communication", subcategory: "Protesting Appropriately", gradeLevel: ["Middle", "High"], condition: "When experiencing a disagreement with a peer or adult directive they find unfair", behavior: "the student will advocate for themselves using a respectful tone and provide a reason for their perspective", criteria: "in 4 out of 5 opportunities across 4 consecutive weeks, as measured by staff observation." },
  // Expressing Needs
  { id: 56, category: "Communication", subcategory: "Expressing Needs", gradeLevel: ["PreK", "Elementary"], condition: "When experiencing discomfort, hunger, thirst, or need to use the restroom", behavior: "the student will communicate their need to an adult using their communication system", criteria: "within 2 minutes of the need arising in 4 out of 5 opportunities across 10 consecutive school days, as measured by staff data." },
  { id: 57, category: "Communication", subcategory: "Expressing Needs", gradeLevel: ["Elementary", "Middle"], condition: "When feeling confused, overwhelmed, or needing a sensory break", behavior: "the student will communicate their internal state to a trusted adult using pre-taught phrases or visual supports", criteria: "in 80% of observed situations across 4 consecutive weeks, as measured by teacher and counselor data." },
  // Asking for Help
  { id: 58, category: "Communication", subcategory: "Asking for Help", gradeLevel: ["PreK", "Elementary"], condition: "When unable to complete a task independently", behavior: "the student will request help from an adult or peer using an appropriate method (raising hand, help card, verbal request)", criteria: "in 4 out of 5 opportunities across 10 consecutive school days, as measured by teacher observation." },
  { id: 59, category: "Communication", subcategory: "Asking for Help", gradeLevel: ["Elementary", "Middle"], condition: "When stuck on an academic task for more than 2 minutes", behavior: "the student will attempt at least one strategy independently, then ask for help using an appropriate voice and method", criteria: "in 80% of opportunities across 3 consecutive weeks, as measured by teacher data." },
  { id: 60, category: "Communication", subcategory: "Asking for Help", gradeLevel: ["Middle", "High"], condition: "When facing academic or social challenges", behavior: "the student will identify the specific type of help needed and approach an appropriate person (teacher, counselor, peer) to request assistance", criteria: "in 4 out of 5 opportunities across 4 consecutive weeks, as measured by teacher and counselor observation." },
  // Functional Communication
  { id: 61, category: "Communication", subcategory: "Functional Communication", gradeLevel: ["PreK", "Elementary"], condition: "Across all school settings", behavior: "the student will use their functional communication system to express at least 5 different communicative functions (request, reject, comment, greet, answer)", criteria: "with 80% independence across 10 consecutive school days, as measured by communication data logs." },
  { id: 62, category: "Communication", subcategory: "Functional Communication", gradeLevel: ["PreK"], condition: "During daily school activities", behavior: "the student will use at least 20 functional words/signs/symbols to communicate throughout the day", criteria: "averaging 20+ communicative acts per day across 5 consecutive school days, as measured by staff tally data." },
  { id: 63, category: "Communication", subcategory: "Functional Communication", gradeLevel: ["Elementary", "Middle"], condition: "When previously engaging in problem behavior to communicate", behavior: "the student will use the identified functionally equivalent replacement behavior (FCR) instead of the problem behavior", criteria: "in 80% of opportunities across 4 consecutive weeks, as measured by ABC data and frequency counts." },

  // ========== ACADEMIC ENGAGEMENT ==========
  // On-Task Behavior
  { id: 64, category: "Academic Engagement", subcategory: "On-Task Behavior", gradeLevel: ["PreK", "Elementary"], condition: "During teacher-directed instruction", behavior: "the student will demonstrate on-task behavior (eyes on speaker, materials ready, following along)", criteria: "for at least 10 consecutive minutes in 4 out of 5 opportunities per day across 10 consecutive school days, as measured by momentary time sampling." },
  { id: 65, category: "Academic Engagement", subcategory: "On-Task Behavior", gradeLevel: ["Elementary", "Middle"], condition: "During independent work time", behavior: "the student will remain on-task (working on assigned material, not engaging with non-related items/peers)", criteria: "for 80% of the work period, as measured by 2-minute interval recording across 10 consecutive school days." },
  { id: 66, category: "Academic Engagement", subcategory: "On-Task Behavior", gradeLevel: ["Middle", "High"], condition: "During class lectures and independent assignments", behavior: "the student will demonstrate academic engagement (taking notes, participating, working on assignments)", criteria: "for 85% of the class period across 4 consecutive weeks, as measured by momentary time sampling at 5-minute intervals." },
  // Work Completion
  { id: 67, category: "Academic Engagement", subcategory: "Work Completion", gradeLevel: ["Elementary", "Middle"], condition: "When given a classroom assignment", behavior: "the student will complete and submit the assignment within the allotted time", criteria: "for 80% of assignments across 4 consecutive weeks, as measured by assignment completion logs." },
  { id: 68, category: "Academic Engagement", subcategory: "Work Completion", gradeLevel: ["Middle", "High"], condition: "When given classwork and homework assignments", behavior: "the student will complete and turn in all assignments by the due date", criteria: "for 75% of all assignments across the grading period, as measured by teacher gradebook records." },
  { id: 69, category: "Academic Engagement", subcategory: "Work Completion", gradeLevel: ["PreK", "Elementary"], condition: "During structured academic activities (worksheets, art projects, writing tasks)", behavior: "the student will complete the assigned task to the standard set by the teacher", criteria: "in 4 out of 5 activities per day across 2 consecutive weeks, as measured by work samples and teacher data." },
  // Following Directions
  { id: 70, category: "Academic Engagement", subcategory: "Following Directions", gradeLevel: ["PreK", "Elementary"], condition: "When given a 1-2 step direction by the teacher", behavior: "the student will follow the direction within 30 seconds", criteria: "in 4 out of 5 opportunities per day across 10 consecutive school days, as measured by teacher data." },
  { id: 71, category: "Academic Engagement", subcategory: "Following Directions", gradeLevel: ["Elementary", "Middle"], condition: "When given multi-step directions (3+ steps)", behavior: "the student will follow all steps of the direction in the correct order", criteria: "in 80% of opportunities across 3 consecutive weeks, as measured by teacher observation." },
  { id: 72, category: "Academic Engagement", subcategory: "Following Directions", gradeLevel: ["Middle", "High"], condition: "When given verbal or written directions for an assignment", behavior: "the student will read/listen to all directions before beginning and follow them accurately", criteria: "in 80% of assignments across 4 consecutive weeks, as measured by assignment accuracy and teacher observation." },
  // Transitioning
  { id: 73, category: "Academic Engagement", subcategory: "Transitioning", gradeLevel: ["PreK", "Elementary"], condition: "When transitioning between activities or locations", behavior: "the student will stop the current activity, gather needed materials, and move to the next activity/location", criteria: "within 2 minutes with no more than 1 verbal prompt in 4 out of 5 transitions per day across 10 consecutive school days, as measured by teacher data." },
  { id: 74, category: "Academic Engagement", subcategory: "Transitioning", gradeLevel: ["Elementary", "Middle"], condition: "When transitioning between classes or activities", behavior: "the student will arrive at the next class/activity on time, with materials, and ready to learn", criteria: "in 90% of transitions across 4 consecutive weeks, as measured by teacher check-in data." },
  { id: 75, category: "Academic Engagement", subcategory: "Transitioning", gradeLevel: ["PreK"], condition: "When a visual or auditory signal indicates transition time", behavior: "the student will stop their current activity and follow the transition routine (clean up, line up, move to next area)", criteria: "within 1 minute with visual support in 4 out of 5 transitions per day across 2 consecutive weeks, as measured by teacher observation." },
  // Attending to Instruction
  { id: 76, category: "Academic Engagement", subcategory: "Attending to Instruction", gradeLevel: ["PreK", "Elementary"], condition: "During whole-group or small-group instruction", behavior: "the student will attend to the teacher (eyes on teacher, body facing forward, responding when called upon)", criteria: "for at least 80% of the instructional period across 10 consecutive school days, as measured by momentary time sampling." },
  { id: 77, category: "Academic Engagement", subcategory: "Attending to Instruction", gradeLevel: ["Elementary", "Middle"], condition: "During direct instruction", behavior: "the student will demonstrate attending behavior by taking notes, asking relevant questions, and responding to teacher prompts", criteria: "in 4 out of 5 class sessions per week across 4 consecutive weeks, as measured by teacher observation checklist." },
  { id: 78, category: "Academic Engagement", subcategory: "Attending to Instruction", gradeLevel: ["Middle", "High"], condition: "During lectures and class discussions", behavior: "the student will actively participate by taking notes and contributing at least one relevant comment or question per class", criteria: "in 80% of class sessions across 4 consecutive weeks, as measured by participation log and teacher observation." },

  // ========== DAILY LIVING / INDEPENDENCE ==========
  // Self-Care
  { id: 79, category: "Daily Living / Independence", subcategory: "Self-Care", gradeLevel: ["PreK", "Elementary"], condition: "During the school day", behavior: "the student will independently manage personal hygiene tasks (handwashing, using the restroom, wiping face after eating)", criteria: "completing all steps of the task analysis with 80% independence across 10 consecutive school days, as measured by staff data." },
  { id: 80, category: "Daily Living / Independence", subcategory: "Self-Care", gradeLevel: ["PreK", "Elementary"], condition: "During lunch time", behavior: "the student will independently open food containers, eat neatly, and clean up their eating area", criteria: "with no more than 1 verbal prompt per lunch across 10 consecutive school days, as measured by staff observation." },
  { id: 81, category: "Daily Living / Independence", subcategory: "Self-Care", gradeLevel: ["Elementary", "Middle"], condition: "Before and after PE or outdoor activities", behavior: "the student will independently manage dressing tasks (changing clothes, tying shoes, zipping jacket)", criteria: "completing all steps within 5 minutes with 80% independence across 10 consecutive school days, as measured by staff data." },
  // Organization
  { id: 82, category: "Daily Living / Independence", subcategory: "Organization", gradeLevel: ["Elementary", "Middle"], condition: "At the beginning and end of each school day", behavior: "the student will organize their materials (binder, folders, backpack) according to the established organizational system", criteria: "with 80% accuracy across 4 consecutive weeks, as measured by weekly organizational checks." },
  { id: 83, category: "Daily Living / Independence", subcategory: "Organization", gradeLevel: ["Middle", "High"], condition: "Throughout the school week", behavior: "the student will maintain an organized binder/folder system and use a planner to record assignments and due dates", criteria: "with 80% of assignments recorded and materials organized across 4 consecutive weeks, as measured by weekly planner and binder checks." },
  { id: 84, category: "Daily Living / Independence", subcategory: "Organization", gradeLevel: ["PreK", "Elementary"], condition: "During clean-up time", behavior: "the student will put materials back in their designated locations", criteria: "in 4 out of 5 clean-up periods per day across 10 consecutive school days, as measured by teacher observation." },
  // Time Management
  { id: 85, category: "Daily Living / Independence", subcategory: "Time Management", gradeLevel: ["Middle", "High"], condition: "When given a long-term project or multi-step assignment", behavior: "the student will break the task into smaller steps, create a timeline, and complete each step by the self-set deadline", criteria: "completing 80% of steps on time across 3 consecutive assignments, as measured by teacher check-ins and project timelines." },
  { id: 86, category: "Daily Living / Independence", subcategory: "Time Management", gradeLevel: ["Elementary", "Middle"], condition: "During independent work periods", behavior: "the student will use a timer or visual schedule to pace their work and complete tasks within the allotted time", criteria: "in 80% of work periods across 3 consecutive weeks, as measured by teacher observation and work completion data." },
  { id: 87, category: "Daily Living / Independence", subcategory: "Time Management", gradeLevel: ["Middle", "High"], condition: "Throughout the school day", behavior: "the student will arrive to all classes within 1 minute of the bell and use passing time appropriately", criteria: "with 90% on-time arrival across 4 consecutive weeks, as measured by tardy logs." },
  // Following Routines
  { id: 88, category: "Daily Living / Independence", subcategory: "Following Routines", gradeLevel: ["PreK", "Elementary"], condition: "During the morning arrival routine", behavior: "the student will independently complete all routine steps (unpack, turn in folder, make lunch choice, go to seat) using a visual checklist", criteria: "completing all steps within 10 minutes with no more than 1 prompt across 10 consecutive school days, as measured by teacher data." },
  { id: 89, category: "Daily Living / Independence", subcategory: "Following Routines", gradeLevel: ["Elementary", "Middle"], condition: "During daily classroom routines (arrival, transitions, dismissal)", behavior: "the student will follow the established routine independently", criteria: "in 90% of routines per day across 4 consecutive weeks, as measured by teacher checklist data." },
  { id: 90, category: "Daily Living / Independence", subcategory: "Following Routines", gradeLevel: ["PreK"], condition: "During the end-of-day routine", behavior: "the student will follow the visual schedule to pack their backpack, gather belongings, and line up for dismissal", criteria: "completing all steps with no more than 2 prompts across 10 consecutive school days, as measured by staff data." },

  // ========== ADDITIONAL GOALS TO REACH 120+ ==========
  // More Behavior Reduction
  { id: 91, category: "Behavior Reduction", subcategory: "Aggression", gradeLevel: ["PreK"], condition: "During play-based activities with peers", behavior: "the student will use gentle hands and keep a safe body", criteria: "with no more than 1 incident of physical aggression per day across 10 consecutive school days, as measured by incident tracking." },
  { id: 92, category: "Behavior Reduction", subcategory: "Disruption", gradeLevel: ["High"], condition: "During class instruction and independent work", behavior: "the student will use electronics (phone, earbuds) only during teacher-approved times", criteria: "with no more than 1 redirection per class period across 4 consecutive weeks, as measured by teacher data." },
  { id: 93, category: "Behavior Reduction", subcategory: "Non-Compliance", gradeLevel: ["Middle", "High"], condition: "When given a directive they disagree with", behavior: "the student will comply with the directive first, then use the appropriate channel (after class, office hours, counselor) to discuss their concern", criteria: "in 80% of situations across 4 consecutive weeks, as measured by staff observation." },
  { id: 94, category: "Behavior Reduction", subcategory: "Elopement", gradeLevel: ["Middle", "High"], condition: "When feeling the urge to leave class", behavior: "the student will use a pre-arranged signal (break card, hand signal) to communicate the need for a break and wait for staff acknowledgment before leaving", criteria: "in 100% of situations across 4 consecutive weeks, as measured by break card logs and staff reports." },
  { id: 95, category: "Behavior Reduction", subcategory: "Task Refusal", gradeLevel: ["High"], condition: "When presented with a challenging or non-preferred assignment", behavior: "the student will begin the task within 5 minutes and work for at least 10 minutes before requesting a modification", criteria: "in 80% of opportunities across 4 consecutive weeks, as measured by teacher observation." },

  // More Social Skills
  { id: 96, category: "Social Skills", subcategory: "Peer Interaction", gradeLevel: ["PreK"], condition: "During parallel play or small group activities", behavior: "the student will engage in interactive play with at least one peer (sharing, turn-taking, role-playing)", criteria: "for at least 5 minutes per play session in 4 out of 5 sessions across 2 consecutive weeks, as measured by teacher observation." },
  { id: 97, category: "Social Skills", subcategory: "Cooperation", gradeLevel: ["Elementary", "Middle"], condition: "During PE, art, or other specials classes", behavior: "the student will follow game/activity rules and accept outcomes (winning/losing) without arguing or withdrawing", criteria: "in 4 out of 5 activities across 3 consecutive weeks, as measured by specials teacher feedback." },
  { id: 98, category: "Social Skills", subcategory: "Social Cues", gradeLevel: ["High"], condition: "During group work and social interactions", behavior: "the student will recognize when a peer is uninterested or uncomfortable and adjust their behavior accordingly (change topic, give space)", criteria: "in 80% of observed interactions across 4 consecutive weeks, as measured by staff observation." },
  { id: 99, category: "Social Skills", subcategory: "Conversation Skills", gradeLevel: ["PreK"], condition: "During snack time or free choice", behavior: "the student will use at least 2-word phrases to communicate with peers", criteria: "in at least 3 interactions per session across 10 consecutive school days, as measured by staff data." },

  // More Self-Regulation
  { id: 100, category: "Self-Regulation", subcategory: "Emotional Regulation", gradeLevel: ["High"], condition: "When experiencing anxiety about academic performance or social situations", behavior: "the student will implement a pre-planned anxiety management strategy (grounding technique, journaling, talking to counselor)", criteria: "before the anxiety escalates to avoidance behavior in 80% of situations across 4 consecutive weeks, as measured by self-report and counselor data." },
  { id: 101, category: "Self-Regulation", subcategory: "Self-Monitoring", gradeLevel: ["PreK"], condition: "During structured activities", behavior: "the student will respond to a teacher check-in ('How is your body?') by identifying if their body is calm, wiggly, or upset", criteria: "correctly identifying their state in 4 out of 5 check-ins per day across 2 consecutive weeks, as measured by teacher data." },
  { id: 102, category: "Self-Regulation", subcategory: "Frustration Tolerance", gradeLevel: ["High"], condition: "When receiving a grade lower than expected", behavior: "the student will review the feedback, identify areas for improvement, and create an action plan rather than giving up or becoming verbally aggressive", criteria: "in 4 out of 5 opportunities across the grading period, as measured by teacher observation and student reflection forms." },
  { id: 103, category: "Self-Regulation", subcategory: "Coping Strategies", gradeLevel: ["PreK"], condition: "When upset during a transition or separation from caregiver", behavior: "the student will use a comfort item or engage in a calming routine (look at family photo, hug stuffed animal, go to cozy corner) with adult support fading over time", criteria: "recovering to a calm state within 5 minutes in 4 out of 5 opportunities across 3 consecutive weeks, as measured by staff data." },

  // More Communication
  { id: 104, category: "Communication", subcategory: "Functional Communication", gradeLevel: ["Middle", "High"], condition: "During all school settings", behavior: "the student will use age-appropriate communication to express their thoughts, needs, and feelings instead of engaging in problem behavior", criteria: "in 90% of opportunities across 4 consecutive weeks, as measured by behavior data and communication logs." },
  { id: 105, category: "Communication", subcategory: "Requesting", gradeLevel: ["Middle", "High"], condition: "When needing academic support or accommodations", behavior: "the student will self-advocate by approaching the teacher before or after class to request help, extended time, or clarification", criteria: "in at least 3 instances per week across 4 consecutive weeks, as measured by teacher logs." },
  { id: 106, category: "Communication", subcategory: "Expressing Needs", gradeLevel: ["Middle", "High"], condition: "When feeling overwhelmed, anxious, or emotionally dysregulated", behavior: "the student will communicate their emotional state to a trusted adult using pre-identified language (e.g., 'I need a minute,' 'I'm feeling overwhelmed')", criteria: "in 4 out of 5 situations across 4 consecutive weeks, as measured by counselor and teacher observation." },

  // More Academic Engagement
  { id: 107, category: "Academic Engagement", subcategory: "On-Task Behavior", gradeLevel: ["High"], condition: "During independent study or online learning", behavior: "the student will remain focused on academic material without accessing non-academic websites or apps", criteria: "for 80% of the study period across 4 consecutive weeks, as measured by screen time monitoring and teacher check-ins." },
  { id: 108, category: "Academic Engagement", subcategory: "Work Completion", gradeLevel: ["PreK"], condition: "During table-time activities", behavior: "the student will remain seated and work on the assigned activity until completion or until the timer signals the end", criteria: "in 4 out of 5 table-time activities per day across 2 consecutive weeks, as measured by teacher observation." },
  { id: 109, category: "Academic Engagement", subcategory: "Attending to Instruction", gradeLevel: ["High"], condition: "During 50+ minute class periods", behavior: "the student will demonstrate sustained attention by taking organized notes and asking at least one relevant question per class", criteria: "in 80% of class sessions across 4 consecutive weeks, as measured by note-check and participation log." },
  { id: 110, category: "Academic Engagement", subcategory: "Transitioning", gradeLevel: ["Middle", "High"], condition: "When transitioning between classes during passing periods", behavior: "the student will go directly to their next class without extended stops or detours", criteria: "arriving on time to 90% of classes across 4 consecutive weeks, as measured by attendance records." },

  // More Daily Living
  { id: 111, category: "Daily Living / Independence", subcategory: "Self-Care", gradeLevel: ["Middle", "High"], condition: "Throughout the school day", behavior: "the student will independently manage personal hygiene and appearance to age-appropriate standards", criteria: "as rated 'independent' on a daily hygiene checklist across 4 consecutive weeks, as measured by staff observation." },
  { id: 112, category: "Daily Living / Independence", subcategory: "Organization", gradeLevel: ["High"], condition: "When managing multiple classes and extracurricular activities", behavior: "the student will use a digital or paper planning system to track all assignments, deadlines, and commitments", criteria: "with 85% of items accurately recorded and completed on time across 4 consecutive weeks, as measured by planner checks and grade reports." },
  { id: 113, category: "Daily Living / Independence", subcategory: "Following Routines", gradeLevel: ["Middle", "High"], condition: "At the start of each class period", behavior: "the student will independently follow the class entry routine (sit down, take out materials, begin bell-ringer activity)", criteria: "within 2 minutes of the bell in 90% of class periods across 4 consecutive weeks, as measured by teacher observation." },
  { id: 114, category: "Daily Living / Independence", subcategory: "Time Management", gradeLevel: ["Elementary"], condition: "During classroom activities with set time limits", behavior: "the student will use a visual timer to monitor their pace and complete tasks within the given timeframe", criteria: "in 4 out of 5 timed activities per day across 2 consecutive weeks, as measured by teacher observation." },
  { id: 115, category: "Daily Living / Independence", subcategory: "Following Routines", gradeLevel: ["PreK", "Elementary"], condition: "During fire drills, lockdown drills, and emergency procedures", behavior: "the student will follow the established safety routine with adult guidance", criteria: "completing all steps of the safety routine in 4 out of 5 drill situations across the school year, as measured by staff observation." },

  // Additional goals for comprehensive coverage
  { id: 116, category: "Social Skills", subcategory: "Peer Interaction", gradeLevel: ["High"], condition: "During group projects and extracurricular activities", behavior: "the student will work collaboratively with assigned partners, even those who are not preferred peers", criteria: "receiving 'meets expectations' or higher on collaboration rubrics for 80% of group assignments across the grading period." },
  { id: 117, category: "Communication", subcategory: "Asking for Help", gradeLevel: ["PreK"], condition: "When struggling with a task (puzzle, building, drawing)", behavior: "the student will bring the item to an adult or say/sign 'help' instead of crying or throwing the item", criteria: "in 4 out of 5 opportunities across 10 consecutive school days, as measured by staff observation." },
  { id: 118, category: "Self-Regulation", subcategory: "Anger Management", gradeLevel: ["High"], condition: "When provoked by peers (teasing, exclusion, rumors)", behavior: "the student will use a de-escalation strategy (deep breathing, walking away, reporting to an adult) instead of verbal or physical retaliation", criteria: "in 4 out of 5 situations across 4 consecutive weeks, as measured by incident data and self-report." },
  { id: 119, category: "Behavior Reduction", subcategory: "Self-Injury", gradeLevel: ["Middle", "High"], condition: "When experiencing emotional distress or sensory overload", behavior: "the student will use pre-identified replacement behaviors (fidget tool, journaling, requesting counselor visit) instead of self-injurious behavior", criteria: "reducing SIB to 0 incidents per week for 4 consecutive weeks, as measured by staff observation and incident reports." },
  { id: 120, category: "Academic Engagement", subcategory: "Following Directions", gradeLevel: ["PreK"], condition: "During group activities and circle time", behavior: "the student will follow simple one-step directions (sit down, come here, put it away) given by the teacher", criteria: "within 10 seconds in 4 out of 5 opportunities per session across 10 consecutive school days, as measured by teacher data." },
].map(g => ({
  ...g,
  goal: `${g.condition}, ${g.behavior}, ${g.criteria}`
}));
