"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import type { GeneratedBIP } from "./bipGenerator";
import { bipToText } from "./bipGenerator";

interface BIPOutputProps {
  bip: GeneratedBIP;
  onReset: () => void;
}

export function BIPOutput({ bip, onReset }: BIPOutputProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(bipToText(bip));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* fallback */ }
  };

  return (
    <div className="rounded-3xl border border-emerald-200/80 bg-white shadow-[0_25px_60px_-45px_rgba(15,23,42,0.6)]">
      <div className="border-b border-emerald-100 bg-gradient-to-r from-emerald-800 via-emerald-700 to-emerald-600 px-6 py-6 text-white print:bg-emerald-800">
        <span className="text-xs uppercase tracking-[0.3em] text-emerald-100">Complete</span>
        <h2 className="mt-1 text-2xl font-semibold sm:text-3xl">Behavior Intervention Plan</h2>
        <p className="mt-1 text-sm text-emerald-50/90">Generated by Behavior School</p>
      </div>

      <div className="space-y-6 px-6 py-6 print:space-y-4">
        {/* Student Info */}
        <InfoTable rows={[
          ["Student", bip.studentInfo.name],
          ["Grade", bip.studentInfo.grade],
          ["School", bip.studentInfo.school],
          ["Date of FBA", bip.studentInfo.dateOfFBA],
          ["Date of BIP", bip.studentInfo.dateOfBIP],
          ["Team", bip.studentInfo.teamMembers],
        ]} />

        {/* Target Behavior for Reduction */}
        <Section title="Target Behavior for Reduction" subtitle="What is the observable and measurable target behavior for reduction?">
          <div className="space-y-2">
            <LabeledText label="Target Behavior" value={bip.targetBehaviorForReduction.behavior} />
            <LabeledText label="Operational Definition" value={bip.targetBehaviorForReduction.definition} />
            {bip.targetBehaviorForReduction.precursors && (
              <LabeledText label="Precursors" value={bip.targetBehaviorForReduction.precursors} />
            )}
            {bip.targetBehaviorForReduction.triggers && (
              <LabeledText label="Triggers" value={bip.targetBehaviorForReduction.triggers} />
            )}
          </div>
        </Section>

        {/* Baseline for Problem Behavior */}
        <Section title="Baseline for Problem Behavior" subtitle="For how long or how often is the problem behavior occurring?">
          <p className="text-sm text-slate-700">{bip.problemBehaviorBaseline || "See FBA data."}</p>
        </Section>

        {/* Function */}
        <Section title="Function" subtitle="What is the hypothesized reason why the behavior occurs? (to get / to avoid / sensory regulation)">
          <p className="text-sm text-slate-700">{bip.functionStatement}</p>
        </Section>

        {/* Replacement Behavior */}
        <Section title="Replacement Behavior" subtitle="What should the student do instead of the problem behavior?">
          <p className="text-sm text-slate-700">{bip.replacementBehavior}</p>
        </Section>

        {/* Baseline for Replacement Behavior */}
        <Section title="Baseline for Replacement Behavior" subtitle="For how long or how often is the replacement behavior occurring?">
          <p className="text-sm text-slate-700">{bip.replacementBehaviorBaseline || "Not yet observed / occurring at low rates"}</p>
        </Section>

        {/* Antecedent Interventions */}
        <Section title="Antecedent Interventions" subtitle="What interventions will reduce the likelihood of the problem behavior before it occurs?">
          <StrategyList items={bip.antecedentInterventions} />
        </Section>

        {/* Reinforcement Procedures */}
        <Section title="Reinforcement Procedures" subtitle="How will the replacement or other positive behaviors be reinforced?">
          <StrategyList items={bip.reinforcementProcedures} />
        </Section>

        {/* Consequence Interventions */}
        <Section title="Consequence Interventions" subtitle="What will others do when the problem behavior occurs to decrease the future likelihood?">
          <StrategyList items={bip.consequenceInterventions} />
        </Section>

        {/* Data Collection */}
        <Section title="Data Collection" subtitle="What data will be collected? By when? By whom?">
          <div className="overflow-x-auto">
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="bg-slate-100">
                  <th className="border border-slate-200 px-3 py-2 text-left font-semibold text-slate-700">Data to be collected</th>
                  <th className="border border-slate-200 px-3 py-2 text-left font-semibold text-slate-700">Procedures</th>
                  <th className="border border-slate-200 px-3 py-2 text-left font-semibold text-slate-700">Person responsible</th>
                  <th className="border border-slate-200 px-3 py-2 text-left font-semibold text-slate-700">How often</th>
                </tr>
              </thead>
              <tbody>
                {bip.dataCollectionMatrix.map((row, i) => (
                  <tr key={i}>
                    <td className="border border-slate-200 px-3 py-2 font-medium text-slate-800">{row.behaviorType}</td>
                    <td className="border border-slate-200 px-3 py-2 text-slate-600">{row.procedures}</td>
                    <td className="border border-slate-200 px-3 py-2 text-slate-600">{row.personResponsible}</td>
                    <td className="border border-slate-200 px-3 py-2 text-slate-600">{row.frequency}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Section>

        {/* Criteria for Success */}
        <Section title="Criteria for Success" subtitle="How will the plan be faded? How will you know when the plan is successful?">
          <p className="text-sm text-slate-700">{bip.successCriteria}</p>
        </Section>

        {/* Goals */}
        <Section title="Behavior Intervention Plan: Goals">
          <p className="text-xs italic text-slate-500 mb-3">When the team meets to evaluate goals, record whether the goals were met by the expected date.</p>
          <div className="space-y-4">
            {bip.goals.map((goal, i) => (
              <div key={i} className="rounded-xl border border-slate-200 p-4">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-semibold text-slate-800">Goal #{i + 1} — {goal.goalType === "reduction" ? "Reduction" : goal.goalType === "replacement" ? "Replacement" : "Skill Building"}</span>
                  <span className="text-xs text-slate-400">Goal Met: ________</span>
                </div>
                <p className="text-sm text-slate-700">{goal.goalText}</p>
              </div>
            ))}
          </div>
        </Section>

        {/* Crisis Plan */}
        {bip.crisisPlan && (
          <Section title="Crisis / Safety Plan">
            <div className="rounded-xl border border-red-200 bg-red-50/50 p-4">
              <ul className="space-y-1">
                {bip.crisisPlan.map((item, i) => (
                  <li key={i} className={`text-sm text-red-900 ${item.match(/^\d+\./) ? "pl-4" : item === "" ? "" : ""}`}>
                    {item || <br />}
                  </li>
                ))}
              </ul>
            </div>
          </Section>
        )}

        {/* Generalization */}
        <Section title="Generalization Plan">
          <StrategyList items={bip.generalizationPlan} />
        </Section>

        {/* Actions */}
        <div className="flex flex-wrap gap-3 border-t border-slate-200 pt-6 print:hidden">
          <Button onClick={handleCopy} className="bg-emerald-600 hover:bg-emerald-700">
            {copied ? "Copied!" : "Copy Full BIP"}
          </Button>
          <Button variant="outline" onClick={() => window.print()}>Print / Save as PDF</Button>
          <Button variant="outline" onClick={onReset}>Start Over</Button>
        </div>

        <p className="text-center text-xs text-slate-400 print:text-slate-600">
          Generated by Behavior School — behaviorschool.com/fba-to-bip<br />
          This BIP should be reviewed and customized by the student&apos;s behavior support team.
        </p>
      </div>
    </div>
  );
}

// ─── Sub-components ─────────────────────────────────────────────────────

function Section({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3 break-inside-avoid">
      <div className="rounded-lg bg-slate-100 border border-slate-200 px-4 py-2">
        <h3 className="text-sm font-bold uppercase text-slate-800">{title}</h3>
        {subtitle && <p className="text-xs text-slate-500 mt-0.5">{subtitle}</p>}
      </div>
      <div className="px-2">{children}</div>
    </div>
  );
}

function StrategyList({ items }: { items: string[] }) {
  return (
    <ul className="space-y-2">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
          <span className="mt-1 text-emerald-600">•</span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}

function InfoTable({ rows }: { rows: [string, string][] }) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-slate-50/80 p-4">
      <div className="grid gap-2 text-sm sm:grid-cols-2">
        {rows.map(([label, value]) => (
          <p key={label}><span className="font-semibold text-slate-700">{label}:</span> {value}</p>
        ))}
      </div>
    </div>
  );
}

function LabeledText({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <span className="text-sm font-semibold text-slate-800">{label}:</span>{" "}
      <span className="text-sm text-slate-700">{value}</span>
    </div>
  );
}
