"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import type { GeneratedBIP } from "./bipGenerator";
import { bipToText } from "./bipGenerator";

interface BIPOutputProps {
  bip: GeneratedBIP;
  onReset: () => void;
}

function Section({ number, title, children }: { number: number; title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3">
      <h3 className="flex items-center gap-2 text-base font-semibold text-slate-900 sm:text-lg">
        <span className="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-600 text-xs font-bold text-white">{number}</span>
        {title}
      </h3>
      {children}
    </div>
  );
}

function StrategyList({ items }: { items: string[] }) {
  return (
    <ul className="space-y-2">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
          <span className="mt-1 text-emerald-600">•</span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}

export function BIPOutput({ bip, onReset }: BIPOutputProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(bipToText(bip));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fallback
    }
  };

  const handlePrint = () => window.print();

  let sectionNum = 0;

  return (
    <div className="rounded-3xl border border-emerald-200/80 bg-white shadow-[0_25px_60px_-45px_rgba(15,23,42,0.6)]">
      <div className="border-b border-emerald-100 bg-gradient-to-r from-emerald-800 via-emerald-700 to-emerald-600 px-6 py-6 text-white print:bg-emerald-800">
        <span className="text-xs uppercase tracking-[0.3em] text-emerald-100">Complete</span>
        <h2 className="mt-1 text-2xl font-semibold sm:text-3xl">Behavior Intervention Plan</h2>
        <p className="mt-1 text-sm text-emerald-50/90">Generated by Behavior School</p>
      </div>

      <div className="space-y-8 px-6 py-6 print:space-y-6">
        {/* Student Info */}
        <div className="rounded-2xl border border-slate-200 bg-slate-50/80 p-4">
          <div className="grid gap-2 text-sm sm:grid-cols-2">
            <p><span className="font-semibold text-slate-700">Student:</span> {bip.studentInfo.name}</p>
            <p><span className="font-semibold text-slate-700">Age:</span> {bip.studentInfo.age}</p>
            <p><span className="font-semibold text-slate-700">Grade:</span> {bip.studentInfo.grade}</p>
            <p><span className="font-semibold text-slate-700">School:</span> {bip.studentInfo.school}</p>
            <p><span className="font-semibold text-slate-700">Date of FBA:</span> {bip.studentInfo.dateOfFBA}</p>
            <p><span className="font-semibold text-slate-700">Date of BIP:</span> {bip.studentInfo.dateOfBIP}</p>
            <p className="sm:col-span-2"><span className="font-semibold text-slate-700">Team:</span> {bip.studentInfo.teamMembers}</p>
          </div>
        </div>

        <Section number={++sectionNum} title="Target Behavior Definitions">
          {bip.behaviorDefinitions.map((b, i) => (
            <div key={i} className="rounded-xl border border-slate-200 bg-white p-4 space-y-1">
              <p className="text-sm font-semibold text-slate-900">{b.name}</p>
              <p className="text-sm text-slate-600"><span className="font-semibold">Definition:</span> {b.definition}</p>
              <div className="flex flex-wrap gap-4 text-xs text-slate-500">
                <span>Frequency: {b.frequency || "—"}</span>
                <span>Duration: {b.duration || "—"}</span>
                <span>Intensity: <span className={b.intensity === "high" ? "text-red-600 font-semibold" : b.intensity === "moderate" ? "text-amber-600 font-semibold" : "text-emerald-600 font-semibold"}>{b.intensity}</span></span>
              </div>
            </div>
          ))}
        </Section>

        <Section number={++sectionNum} title="Function of Behavior">
          <p className="text-sm text-slate-700">{bip.functionSummary}</p>
        </Section>

        <Section number={++sectionNum} title="Antecedent / Prevention Strategies">
          <StrategyList items={bip.antecedentStrategies} />
        </Section>

        <Section number={++sectionNum} title="Teaching Strategies (Replacement Behaviors)">
          <StrategyList items={bip.teachingStrategies} />
        </Section>

        <Section number={++sectionNum} title="Reinforcement Strategies">
          <StrategyList items={bip.reinforcementStrategies} />
        </Section>

        <Section number={++sectionNum} title="Response to Problem Behavior">
          <StrategyList items={bip.responseStrategies} />
        </Section>

        <Section number={++sectionNum} title="Data Collection Plan">
          <StrategyList items={bip.dataCollectionPlan} />
        </Section>

        {bip.crisisPlan && (
          <Section number={++sectionNum} title="Crisis / Safety Plan">
            <div className="rounded-xl border border-red-200 bg-red-50/50 p-4">
              <StrategyList items={bip.crisisPlan} />
            </div>
          </Section>
        )}

        <Section number={++sectionNum} title="Generalization Plan">
          <StrategyList items={bip.generalizationPlan} />
        </Section>

        <Section number={++sectionNum} title="Maintenance Plan">
          <StrategyList items={bip.maintenancePlan} />
        </Section>

        {/* Actions */}
        <div className="flex flex-wrap gap-3 border-t border-slate-200 pt-6 print:hidden">
          <Button onClick={handleCopy} className="bg-emerald-600 hover:bg-emerald-700">
            {copied ? "Copied!" : "Copy Full BIP"}
          </Button>
          <Button variant="outline" onClick={handlePrint}>
            Print / Save as PDF
          </Button>
          <Button variant="outline" onClick={onReset}>
            Start Over
          </Button>
        </div>

        <p className="text-center text-xs text-slate-400 print:text-slate-600">
          Generated by Behavior School — behaviorschool.com/fba-to-bip<br />
          This BIP should be reviewed and customized by the student&apos;s behavior support team.
        </p>
      </div>
    </div>
  );
}
