"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import type { GeneratedACTBIP } from "./actBipGenerator";
import { actBipToText, VALUE_LABELS, ACT_PROCESS_LABELS } from "./actBipGenerator";

interface ACTBIPOutputProps {
  bip: GeneratedACTBIP;
  onReset: () => void;
}

function Section({ number, title, children, accent }: { number: number; title: string; children: React.ReactNode; accent?: "purple" | "emerald" }) {
  const bg = accent === "purple" ? "bg-purple-600" : "bg-emerald-600";
  return (
    <div className="space-y-3">
      <h3 className="flex items-center gap-2 text-base font-semibold text-slate-900 sm:text-lg">
        <span className={`flex h-7 w-7 items-center justify-center rounded-full ${bg} text-xs font-bold text-white`}>{number}</span>
        {title}
      </h3>
      {children}
    </div>
  );
}

function StrategyList({ items }: { items: string[] }) {
  return (
    <ul className="space-y-2">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
          <span className="mt-1 text-emerald-600">•</span>
          <span dangerouslySetInnerHTML={{ __html: item.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>") }} />
        </li>
      ))}
    </ul>
  );
}

export function ACTBIPOutput({ bip, onReset }: ACTBIPOutputProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(actBipToText(bip));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* fallback */ }
  };

  const handlePrint = () => window.print();

  let sectionNum = 0;

  return (
    <div className="rounded-3xl border border-purple-200/80 bg-white shadow-[0_25px_60px_-45px_rgba(15,23,42,0.6)]">
      {/* Header */}
      <div className="border-b border-purple-100 bg-gradient-to-r from-purple-800 via-purple-700 to-emerald-700 px-6 py-6 text-white print:bg-purple-800">
        <span className="text-xs uppercase tracking-[0.3em] text-purple-100">Complete ACT-Informed Report</span>
        <h2 className="mt-1 text-2xl font-semibold sm:text-3xl">ACT-Informed FBA & Behavior Intervention Plan</h2>
        <p className="mt-1 text-sm text-purple-50/90">Generated by Behavior School</p>
      </div>

      <div className="space-y-8 px-6 py-6 print:space-y-6">
        {/* Student Info */}
        <div className="rounded-2xl border border-slate-200 bg-slate-50/80 p-4">
          <div className="grid gap-2 text-sm sm:grid-cols-2">
            <p><span className="font-semibold text-slate-700">Student:</span> {bip.studentInfo.name}</p>
            <p><span className="font-semibold text-slate-700">Age:</span> {bip.studentInfo.age}</p>
            <p><span className="font-semibold text-slate-700">Grade:</span> {bip.studentInfo.grade}</p>
            <p><span className="font-semibold text-slate-700">School:</span> {bip.studentInfo.school}</p>
            <p><span className="font-semibold text-slate-700">Date of FBA:</span> {bip.studentInfo.dateOfFBA}</p>
            <p><span className="font-semibold text-slate-700">Date of BIP:</span> {bip.studentInfo.dateOfBIP}</p>
            <p className="sm:col-span-2"><span className="font-semibold text-slate-700">Team:</span> {bip.studentInfo.teamMembers}</p>
          </div>
        </div>

        {/* Part 1: ACT-Informed FBA */}
        <div className="rounded-2xl border border-purple-200 bg-purple-50/50 p-4">
          <h2 className="text-lg font-bold text-purple-900">Part 1: ACT-Informed Functional Behavior Assessment</h2>
        </div>

        <Section number={++sectionNum} title="Target Behavior Definitions" accent="emerald">
          {bip.behaviorDefinitions.map((b, i) => (
            <div key={i} className="rounded-xl border border-slate-200 bg-white p-4 space-y-1">
              <p className="text-sm font-semibold text-slate-900">{b.name}</p>
              <p className="text-sm text-slate-600"><span className="font-semibold">Definition:</span> {b.definition}</p>
              <div className="flex flex-wrap gap-4 text-xs text-slate-500">
                <span>Frequency: {b.frequency || "—"}</span>
                <span>Duration: {b.duration || "—"}</span>
                <span>Intensity: <span className={b.intensity === "high" ? "text-red-600 font-semibold" : b.intensity === "moderate" ? "text-amber-600 font-semibold" : "text-emerald-600 font-semibold"}>{b.intensity}</span></span>
              </div>
            </div>
          ))}
        </Section>

        <Section number={++sectionNum} title="Values Assessment" accent="purple">
          <div className="rounded-xl border border-purple-200 bg-purple-50/70 p-4 space-y-3">
            <p className="text-sm font-semibold text-purple-900">Identified Student Values</p>
            <div className="space-y-2">
              {bip.valuesAssessment.valuesDescriptions.map((d, i) => (
                <p key={i} className="text-sm text-purple-800" dangerouslySetInnerHTML={{ __html: d.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>") }} />
              ))}
            </div>
          </div>
        </Section>

        <Section number={++sectionNum} title="Psychological Flexibility Assessment" accent="purple">
          <div className="rounded-xl border border-amber-200 bg-amber-50/70 p-4 space-y-3">
            <p className="text-sm font-semibold text-amber-900">Areas of Psychological Inflexibility</p>
            <div className="space-y-2">
              {bip.psychFlexAssessment.processDescriptions.map((d, i) => (
                <p key={i} className="text-sm text-amber-800" dangerouslySetInnerHTML={{ __html: d.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>") }} />
              ))}
            </div>
          </div>
        </Section>

        <Section number={++sectionNum} title="Functional Analysis (Standard + ACT Lens)" accent="emerald">
          {bip.functionSummary.split("\n\n").map((p, i) => (
            <p key={i} className="text-sm text-slate-700">{p}</p>
          ))}
        </Section>

        {bip.actSettingEventsSummary.length > 0 && (
          <Section number={++sectionNum} title="ACT-Specific Setting Events" accent="purple">
            <StrategyList items={bip.actSettingEventsSummary} />
          </Section>
        )}

        {/* Part 2: ACT-Informed BIP */}
        <div className="rounded-2xl border border-emerald-200 bg-emerald-50/50 p-4">
          <h2 className="text-lg font-bold text-emerald-900">Part 2: ACT-Informed Behavior Intervention Plan</h2>
        </div>

        <Section number={++sectionNum} title="Values-Aligned Replacement Behaviors" accent="purple">
          <StrategyList items={bip.valuesAlignedReplacements} />
        </Section>

        <Section number={++sectionNum} title="Antecedent / Prevention Strategies" accent="emerald">
          <StrategyList items={bip.antecedentStrategies} />
        </Section>

        <Section number={++sectionNum} title="Acceptance-Based Strategies" accent="purple">
          <div className="rounded-xl border border-purple-100 bg-purple-50/40 p-4">
            <StrategyList items={bip.acceptanceStrategies} />
          </div>
        </Section>

        <Section number={++sectionNum} title="Defusion Techniques" accent="purple">
          <div className="rounded-xl border border-purple-100 bg-purple-50/40 p-4">
            <StrategyList items={bip.defusionTechniques} />
          </div>
        </Section>

        <Section number={++sectionNum} title="Values Clarification Activities" accent="purple">
          <StrategyList items={bip.valuesActivities} />
        </Section>

        <Section number={++sectionNum} title="Committed Action Goals" accent="purple">
          <div className="space-y-3">
            {bip.committedActionGoals.map((goal, i) => (
              <div key={i} className="rounded-xl border border-purple-200 bg-white p-4">
                <p className="text-sm font-semibold text-purple-800">Committed Action Goal #{i + 1}</p>
                <p className="mt-1 text-sm text-slate-700">{goal}</p>
              </div>
            ))}
          </div>
        </Section>

        <Section number={++sectionNum} title="Metaphors & Exercises" accent="purple">
          <div className="grid gap-3 sm:grid-cols-2">
            {bip.metaphorsAndExercises.map((m, i) => (
              <div key={i} className="rounded-xl border border-purple-200 bg-purple-50/40 p-4 space-y-2">
                <p className="text-sm font-bold text-purple-900">{m.name}</p>
                <p className="text-xs text-purple-700">{m.description}</p>
                <p className="text-xs text-purple-500">Target: {ACT_PROCESS_LABELS[m.targetProcess].label}</p>
              </div>
            ))}
          </div>
        </Section>

        <Section number={++sectionNum} title="Teaching Strategies" accent="emerald">
          <StrategyList items={bip.teachingStrategies} />
        </Section>

        <Section number={++sectionNum} title="Reinforcement Strategies" accent="emerald">
          <StrategyList items={bip.reinforcementStrategies} />
        </Section>

        <Section number={++sectionNum} title="Response to Problem Behavior" accent="emerald">
          <StrategyList items={bip.responseStrategies} />
        </Section>

        <Section number={++sectionNum} title="Data Collection Plan" accent="emerald">
          <StrategyList items={bip.dataCollectionPlan} />
        </Section>

        <Section number={++sectionNum} title="Values-Consistent Progress Monitoring" accent="purple">
          <div className="rounded-xl border border-purple-100 bg-purple-50/40 p-4">
            <StrategyList items={bip.valuesConsistentMonitoring} />
          </div>
        </Section>

        {bip.crisisPlan && (
          <Section number={++sectionNum} title="Crisis / Safety Plan" accent="emerald">
            <div className="rounded-xl border border-red-200 bg-red-50/50 p-4">
              <StrategyList items={bip.crisisPlan.filter(Boolean)} />
            </div>
          </Section>
        )}

        <Section number={++sectionNum} title="Generalization Plan" accent="emerald">
          <StrategyList items={bip.generalizationPlan} />
        </Section>

        <Section number={++sectionNum} title="Maintenance Plan" accent="emerald">
          <StrategyList items={bip.maintenancePlan} />
        </Section>

        {/* Actions */}
        <div className="flex flex-wrap gap-3 border-t border-slate-200 pt-6 print:hidden">
          <Button onClick={handleCopy} className="bg-purple-600 hover:bg-purple-700">
            {copied ? "Copied!" : "Copy Full Report"}
          </Button>
          <Button variant="outline" onClick={handlePrint}>
            Print / Save as PDF
          </Button>
          <Button variant="outline" onClick={onReset}>
            Start Over
          </Button>
        </div>

        <p className="text-center text-xs text-slate-400 print:text-slate-600">
          Generated by Behavior School — behaviorschool.com/act-fba-bip<br />
          This ACT-informed FBA/BIP should be reviewed and customized by the student&apos;s behavior support team.
        </p>
      </div>
    </div>
  );
}
