name: Netlify Build Monitor

on:
  push:
    branches:
      - main
      - '**'

jobs:
  build_and_monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --quiet

      - name: Lint
        run: npm run lint --silent

      - name: Typecheck
        run: npm run typecheck --silent

      - name: Build (local)
        run: npm run build --silent

      - name: Monitor Netlify deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
          NETLIFY_TIMEOUT_SECS: 1800
          NETLIFY_RETRY_COUNT: 2
          NETLIFY_AUTO_FIX: true
        run: |
          node scripts/netlify-monitor.mjs --site "$NETLIFY_SITE_ID" --token "$NETLIFY_AUTH_TOKEN" --buildHook "$NETLIFY_BUILD_HOOK_URL" --timeout "$NETLIFY_TIMEOUT_SECS" --retry "$NETLIFY_RETRY_COUNT" --autoFix "$NETLIFY_AUTO_FIX"


